---
- name: Instalando o pacote epel-release e mais alguns pacotes b√°sicos do sitema para a instalacao do nginx.
  hosts: webservers
  tasks:
    - name: 
      yum: name={{ item }} update_cache=yes state=present
      with_items:
        - vim
        - git
        - wget
        - curl
